name: Lint Codebase

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Run ESLint to check for console logs
      run: |
        npx eslint . --no-eslintrc --rule 'no-console: ["error", { "allow": ["warn", "error"] }]'
