name: Lint Codebase

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Temporarily append to .eslintignore
      run: |
        if [ -f ".eslintignore" ]; then
          # Check if the file ends with a newline, and add one if it doesn't
          [ -n "$(tail -c 1 .eslintignore)" ] && echo >> .eslintignore
        fi
        echo 'env_validator.js' >> .eslintignore

    - name: Run ESLint to check for console logs
      run: |
        echo 'module.exports = { rules: { "no-console": ["error", { "allow": ["warn", "error"] }] } };' > eslint.config.js
        npx eslint . --config eslint.config.js
        rm eslint.config.js

    - name: Cleanup .eslintignore
      run: git checkout -- .eslintignore
