name: Console Log Linting
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      # Install required dependencies
      - name: Install dependencies
        run: |
          npm install -g @babel/eslint-parser eslint-plugin-react

      # Create ESLint config to disallow all console logs
      - name: Create ESLint config
        run: |
          echo 'module.exports = {
            parser: "@babel/eslint-parser",
            parserOptions: {
              babelOptions: {
                configFile: true,
              },
              ecmaFeatures: {
                jsx: true,
              },
              ecmaVersion: 2018,
              sourceType: "module",
            },
            plugins: ["react"],
            extends: ["plugin:react/recommended"],
            rules: {
              "no-console": "error",
              "react/jsx-uses-react": "off",
              "react/react-in-jsx-scope": "off",
            },
          };' > eslint.config.js

      - name: Run ESLint to check for console logs
        run: |
          npx --no-deprecation eslint '**/*' --config eslint.config.js --no-config-lookup
          rm eslint.config.js