name: Lint Codebase

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Create temporary ESLint config
      run: |
        echo 'module.exports = { rules: { "no-console": ["error", { "allow": ["warn", "error"] }] } };' > eslint.config.js

    - name: Run ESLint to check for console logs
      run: npx eslint . --config eslint.config.js --ignore-pattern 'env-validator.js'

    - name: Cleanup temporary ESLint config
      run: rm eslint.config.js
