name: Lint Codebase

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create temporary ESLint config
      run: |
        echo 'rules:' > .eslintrc.temp.yaml
        echo '  no-console: ["error", { "allow": ["warn", "error"] }]' >> .eslintrc.temp.yaml

    - name: Run ESLint
      run: npx eslint . --config .eslintrc.temp.yaml

    - name: Cleanup temporary ESLint config
      run: rm .eslintrc.temp.yaml
