name: Lint Codebase

on:
  workflow_call: # This allows the workflow to be reusable

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create temporary ESLint config
        run: |
          echo '{' > .eslintrc.temp.json
          echo '  "rules": {' >> .eslintrc.temp.json
          echo '    "no-console": ["error", { "allow": ["warn", "error"] }]' >> .eslintrc.temp.json
          echo '  }' >> .eslintrc.temp.json
          echo '}' >> .eslintrc.temp.json

      - name: Run ESLint
        run: npx eslint . --config .eslintrc.temp.json

      - name: Cleanup temporary ESLint config
        run: rm .eslintrc.temp.json
